version: "3.5"

x-uffizzi:
  ingress:
    service: penpot-frontend
    port: 80

volumes:
  penpot_assets:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80
    volumes:
      - penpot_assets:/opt/data
      - ./.github/uffizzi/nginx:/etc/nginx
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets:/opt/data
      - ./.github/uffizzi/nginx:/etc/nginx
    environment:
      - PENPOT_FLAGS=enable-registration enable-login disable-email-verification enable-smtp
      - PENPOT_DATABASE_URI=postgresql://localhost:5432/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://localhost/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=localhost:1080
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false
    entrypoint: /bin/bash
    command:
    - -c
    - "PENPOT_PUBLIC_URI=$$UFFIZZI_URL /opt/penpot/backend/run.sh"

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      - PENPOT_REDIS_URI=redis://localhost/0
    entrypoint: /bin/sh
    command:
    - -c
    - "node app.js"

  penpot-postgres:
    image: "postgres:15"
    restart: always
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
